model_name: finetuned/TinyLlama/TinyLlama-1.1B-Chat-v1.0/checkpoint-53835

dataset_name: cnn_dailymail
nrow: 30000
col_renames:
  highlights: reference

dataset_output_dir: preprocessed

generation:
  prompt: |
    {article}
    TL;DR:
  max_new_tokens: 128
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  num_return_sequences: 10

scorer:
  type: openai
  openai:
    type: batch
    batch:
      max_request_per_batch: 1500
      max_concurrent: 7
      max_retries: 2
      initial_backoff: 1.0
      poll_interval: 30.0
    model: gpt-5-mini
    prompt: |
      Which of the following summaries does a better job of summarizing the most important points in the given article, without including unimportant or irrelevant details? A good summary is both precise and concise.

      Article:
      {article}

      Summary 1:
      {summary1}

      Summary 2:
      {summary2}

      FIRST provide a one-sentence comparison of the two summaries, explaining which you prefer and why. SECOND, on a new line, state only "1" or "2" to indicate your choice. Your response should use the format:
      Comparison: <one-sentence comparison and explanation>
      Preferred: <"1" or "2">
    preference_pattern: "Preferred:\\s*[\"']?([12])[\"']?"

builder:
  type: cyclic

trainer:
  type: dpo

  dpo:
    logging_steps: 20
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 4
    fp16: True
    num_train_epochs: 1.0
    save_steps: 4000
    save_total_limit: 20
