model_name: finetuned/TinyLlama/TinyLlama-1.1B-Chat-v1.0/checkpoint-53835

dataset_name: cnn_dailymail
nrow: 30000
col_renames:
  highlights: reference
  
output_dir: preprocessed

generation:
  prompt: |
    {article}
    TL;DR:
  max_new_tokens: 128
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  num_return_sequences: 10

get_preference:
  builder: pairwise
  scorer: openai
  # rouge:
  #   type: rougeL
  openai:
    type: batch
    batch:
      max_concurrent: 3
      max_retries: 3
      initial_backoff: 1.0
      poll_interval: 15.0
    model: gpt-5-mini
    prompt: |
      Which of the following summaries does a better job of summarizing the most important points in the given article, without including unimportant or irrelevant details? A good summary is both precise and concise.

      Article:
      {article}

      Summary 1:
      {summary1}

      Summary 2:
      {summary2}

      FIRST provide a one-sentence comparison of the two summaries, explaining which you prefer and why. SECOND, on a new line, state only "1" or "2" to indicate your choice. Your response should use the format:
      Comparison: <one-sentence comparison and explanation>
      Preferred: <"1" or "2">
    preference_pattern: "Preferred:\\s*[\"']?([12])[\"']?"